### ISSUE TITLE
No target provided, or empty target list

### ISSUE THREAD

**Issue by GaelFerrand** [KathanP19/JSFScan.sh#31]
I'm following the procedure and my scans keep failing with "No target provided, or empty target list" error.

Repro steps (on kali linux):
```
git clone clone https://github.com/KathanP19/JSFScan.sh.git
cd JSFScan.sh
sudo chmod +x install.sh
sh ./install.sh
echo "https://mydomain.com" > target.txt
bash JSFScan.sh -l target.txt --all -r -o mydomain
```

This is the stack:
```
(_______/ _____(_______/ _____)                        | |
     _ ( (____  _____ ( (____   ____ _____ ____     ___| |__
 _  | | \____ \|  ___) \____ \ / ___(____ |  _ \   /___|  _ \
| |_| | _____) | |     _____) ( (___/ ___ | | | |_|___ | | | |
 \___/ (______/|_|    (______/ \____\_____|_| |_(_(___/|_| |_|


[+] Started Gathering JsFiles-links

JSFScan.sh: line 21: gau: command not found
JSFScan.sh: line 22: subjs: command not found

[+] Checking for live JsFiles-links

JSFScan.sh: line 25: httpx: command not found

[+] Started gathering Endpoints

=====================================================
Interlace v1.9.5        by Michael Skelton (@codingo_)
                        & Sajeeb Lohani (@sml555_)
=====================================================
Traceback (most recent call last):
  File "/usr/local/bin/interlace", line 33, in <module>
    sys.exit(load_entry_point('Interlace==1.9.5', 'console_scripts', 'interlace')())
  File "/usr/local/lib/python3.9/dist-packages/Interlace-1.9.5-py3.9.egg/Interlace/interlace.py", line 36, in main
  File "/usr/local/lib/python3.9/dist-packages/Interlace-1.9.5-py3.9.egg/Interlace/lib/threader.py", line 101, in __init__
  File "/usr/local/lib/python3.9/dist-packages/Interlace-1.9.5-py3.9.egg/Interlace/interlace.py", line 11, in task_queue_generator_func
  File "/usr/local/lib/python3.9/dist-packages/Interlace-1.9.5-py3.9.egg/Interlace/lib/core/input.py", line 264, in process_data_for_tasks_iterator
Exception: No target provided, or empty target list

[+] Started Finding Secrets in JSFiles

=====================================================
Interlace v1.9.5        by Michael Skelton (@codingo_)
                        & Sajeeb Lohani (@sml555_)
=====================================================
Traceback (most recent call last):
  File "/usr/local/bin/interlace", line 33, in <module>
    sys.exit(load_entry_point('Interlace==1.9.5', 'console_scripts', 'interlace')())
  File "/usr/local/lib/python3.9/dist-packages/Interlace-1.9.5-py3.9.egg/Interlace/interlace.py", line 36, in main
  File "/usr/local/lib/python3.9/dist-packages/Interlace-1.9.5-py3.9.egg/Interlace/lib/threader.py", line 101, in __init__
  File "/usr/local/lib/python3.9/dist-packages/Interlace-1.9.5-py3.9.egg/Interlace/interlace.py", line 11, in task_queue_generator_func
  File "/usr/local/lib/python3.9/dist-packages/Interlace-1.9.5-py3.9.egg/Interlace/lib/core/input.py", line 264, in process_data_for_tasks_iterator
Exception: No target provided, or empty target list

[+] Started to Gather JSFiles locally for Manual Testing

=====================================================
Interlace v1.9.5        by Michael Skelton (@codingo_)
                        & Sajeeb Lohani (@sml555_)
=====================================================
Traceback (most recent call last):
  File "/usr/local/bin/interlace", line 33, in <module>
    sys.exit(load_entry_point('Interlace==1.9.5', 'console_scripts', 'interlace')())
  File "/usr/local/lib/python3.9/dist-packages/Interlace-1.9.5-py3.9.egg/Interlace/interlace.py", line 36, in main
  File "/usr/local/lib/python3.9/dist-packages/Interlace-1.9.5-py3.9.egg/Interlace/lib/threader.py", line 101, in __init__
  File "/usr/local/lib/python3.9/dist-packages/Interlace-1.9.5-py3.9.egg/Interlace/interlace.py", line 11, in task_queue_generator_func
  File "/usr/local/lib/python3.9/dist-packages/Interlace-1.9.5-py3.9.egg/Interlace/lib/core/input.py", line 264, in process_data_for_tasks_iterator
Exception: No target provided, or empty target list

[+] Manually Search For Secrets Using gf or grep in out/


[+] Started Gathering Words From JsFiles-links For Wordlist.


[+] Started Finding Varibles in JSFiles For Possible XSS


[+] Scanning JSFiles For Possible DomXSS

=====================================================
Interlace v1.9.5        by Michael Skelton (@codingo_)
                        & Sajeeb Lohani (@sml555_)
=====================================================
Traceback (most recent call last):
  File "/usr/local/bin/interlace", line 33, in <module>
    sys.exit(load_entry_point('Interlace==1.9.5', 'console_scripts', 'interlace')())
  File "/usr/local/lib/python3.9/dist-packages/Interlace-1.9.5-py3.9.egg/Interlace/interlace.py", line 36, in main
  File "/usr/local/lib/python3.9/dist-packages/Interlace-1.9.5-py3.9.egg/Interlace/lib/threader.py", line 101, in __init__
  File "/usr/local/lib/python3.9/dist-packages/Interlace-1.9.5-py3.9.egg/Interlace/interlace.py", line 11, in task_queue_generator_func
  File "/usr/local/lib/python3.9/dist-packages/Interlace-1.9.5-py3.9.egg/Interlace/lib/core/input.py", line 264, in process_data_for_tasks_iterator
Exception: No target provided, or empty target list

[+] Generating Report!
```

Any idea on the issue ?

**Comment by jagadeeshjs8895** [comment]
Im also facing the same issue.
Please help me to sort out this

**Comment by KathanP19** [comment]
Please try ./install.sh again the issue has been fixed

**Comment by GaelFerrand** [comment]
Still doesn't work for me, exact same issue

**Comment by jagadeeshjs8895** [comment]
Hi

I’m still getting same errors. Is there any other way to install this tool?

**Comment by BartekSmalec** [comment]
Hello, i'm facing the same issue, do you have any solution ?
